package com.dhopd.views;


import com.dhopd.controllers.DBConnection;
import com.dhopd.controllers.OTDBO;
import com.dhopd.controllers.PatientDBO;
import com.dhopd.models.OperationTeam;
import com.dhopd.models.Patient;
import com.dhopd.views.*;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author manish
 * M-Tech Nepal
 */
public class HistoryFrame extends javax.swing.JFrame implements Printable{

     Patient patient ;
    
    
    
    /**
     * Creates new form MyFrame
     */
    public HistoryFrame() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setVisible(true);
        Jbtnupdate.setVisible(false);
    }

    HistoryFrame(int patientId) {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setVisible(true);
        Jbtnsave.setVisible(false);
        patient = new Patient();
        
        PatientDBO pdbo = new PatientDBO();
        patient = pdbo.getPatient(patientId);

        
        try{
            
            
            // SETTING Value In Forms
            
            Jpatient_id.setText(Integer.toString(patient.getPatient_id()));
            Jname.setText(patient.getName());
            Jage.setText(Integer.toString(patient.getAge()));
            Jsex.setText(patient.getSex());
            Jdob.setText(patient.getDob());
            Jaddress.setText(patient.getAddress());
            Jtelephone.setText(patient.getTelephone());
            Jchief_complain.setText(patient.getChief_complain());
            Jhistory_of_illness.setText(patient.getHistory_of_illness());
            Jpast_history.setText(patient.getPast_history());
            Jgeneral.setText(patient.getGeneral());
            Jsystemine.setText(patient.getSystemine());
            Jlocal.setText(patient.getLocal());
            Jlab.setText(patient.getLab());
            Jxray.setText(patient.getXray());
            Jmri.setText(patient.getMri());
            Jsoft_tissue.setSelectedItem((Object) patient.getSoft_tissue());
            Jside.setSelectedItem((Object) patient.getSide());
            Janatomic_location.setSelectedItem((Object) patient.getAnatomic_location());
            Jsub_location.setSelectedItem((Object) patient.getSub_location());
            Jpathology.setSelectedItem((Object) patient.getPathalogical_lesion());
            Jclassification.setText((String) patient.getClassification());
            Jother.setText((String) patient.getOther());
            
            Jprocedure.setSelectedItem((Object) patient.getMgmt_procedure());
            Jimplant.setSelectedItem((Object) patient.getImplant());
            
            Jdate.setText(patient.getDate());
            Jmgmt_other.setText(patient.getMgmt_Other());
            
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        Jmgmg_other = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Jdate = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        Jmgmt_other = new javax.swing.JTextField();
        Jprocedure = new javax.swing.JComboBox();
        Jimplant = new javax.swing.JComboBox();
        Jbtnshow_operation_module = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jpatient_id = new javax.swing.JTextField();
        Jname = new javax.swing.JTextField();
        Jage = new javax.swing.JTextField();
        Jsex = new javax.swing.JTextField();
        Jdob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jaddress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        Jtelephone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jchief_complain = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Jhistory_of_illness = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Jpast_history = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Jgeneral = new javax.swing.JTextField();
        Jsystemine = new javax.swing.JTextField();
        Jlocal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Jxray = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Jct = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Jmri = new javax.swing.JTextField();
        Jlab = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Jsoft_tissue = new javax.swing.JComboBox();
        Jside = new javax.swing.JComboBox();
        Janatomic_location = new javax.swing.JComboBox();
        Jsub_location = new javax.swing.JComboBox();
        Jpathology = new javax.swing.JComboBox();
        Jclassification = new javax.swing.JTextField();
        Jother = new javax.swing.JTextField();
        Jbtnsave = new javax.swing.JButton();
        Jbtnupdate = new javax.swing.JButton();
        Jbtnshow_discharge_module = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("History module");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.pink);

        jScrollPane5.setBorder(null);
        jScrollPane5.setMaximumSize(new java.awt.Dimension(1200, 720));
        jScrollPane5.setMinimumSize(new java.awt.Dimension(200, 200));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examination", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Procedure");

        Jmgmg_other.setBackground(new java.awt.Color(255, 255, 255));
        Jmgmg_other.setText("Other");

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Implant");

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Date");

        Jprocedure.setBackground(new java.awt.Color(255, 255, 255));
        Jprocedure.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AMPUTATION", "ARTHRODESIS", "ARTHROSCOPY", "ARTHROTOMY", "ARTHROCENTESIS", "ASPIRATION", "BONE GRAFTING", "CONSERVATIVE", "CLOSED REDUCTION", "CRPP", "DEBRIDEMENT", "DISCECTOMY", "EXPLORATION & EVACUATION", "EPIDURAL INJECTION", "EXCISION BIOPSY", "EX-FIX", "HEMIARTHROPLASTY", "IMPLANT REMOVAL", "INSTRUMENTATION", "MIPO", "ORIF", "OSTEOCLASIS CLOSED", "OSTEOCLASIS OPEN", "READJUSTMENT", "REIMPLANTATION", "RELOCATION", "POSTERIOR STABILIZATION", "TOTAL HIP ARTHROPLASTY", "TOTAL KNEE ARTHROPLASTY", "MICRODISCECTOMY", "FACET BLOCK", "FLAP PROCEDURE", "REPAIR", "SUTURE", "STSG ", "FULL THICKNESS SKIN GRAFT" }));

        Jimplant.setBackground(new java.awt.Color(255, 255, 255));
        Jimplant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AO TUBULAR", "AUSTIN MOORE HIP PROSTHESIS", "BUTTRESS PLATE", "CCS", "DHS", "DCP", "DCS", "ETHIBOND SUTURE", "HIP SPICA", "ILIZAROV", "HYBRID ILIZAROV", "IMIL", "K NAIL", "K WIRE", "BRACE", "LONG ARM CAST", "LONG LEG CAST", "LOCKING PLATE", "PEDICLE SCREWS", "RECON PLATE", "RUSH PIN", "SHORT ARM CAST", "SHORT LEG CAST", "SCREWS", "SCREWS + TBW", "SHORT LEG BACK SLAB ", "STSG", "SUTURING", "TBW", "THOMPSON HIP PROSTHESIS", "LC-DCP" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jprocedure, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jimplant, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(Jmgmg_other)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jmgmt_other, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Jmgmg_other, jLabel19});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(Jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(Jprocedure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jimplant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jmgmg_other)
                    .addComponent(Jmgmt_other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Jbtnshow_operation_module.setBackground(new java.awt.Color(255, 255, 255));
        Jbtnshow_operation_module.setMnemonic('o');
        Jbtnshow_operation_module.setText("Show Operation Module");
        Jbtnshow_operation_module.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtnshow_operation_moduleActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examination", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hospital No:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sex:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOB");

        Jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnameActionPerformed(evt);
            }
        });

        Jage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JageActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        Jaddress.setColumns(20);
        Jaddress.setRows(5);
        jScrollPane1.setViewportView(Jaddress);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telephone");

        Jtelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtelephoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jpatient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jage, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(Jsex, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jdob)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 184, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jtelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Jtelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Jpatient_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Jname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Jage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(Jsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Jdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examination", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Chief Complain");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("<html>History of <br>Present illness</html>");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("<html>Past History<br> and Comordities</html>");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        Jchief_complain.setColumns(20);
        Jchief_complain.setRows(4);
        jScrollPane2.setViewportView(Jchief_complain);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        Jhistory_of_illness.setColumns(20);
        Jhistory_of_illness.setRows(4);
        jScrollPane3.setViewportView(Jhistory_of_illness);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        Jpast_history.setColumns(20);
        Jpast_history.setRows(4);
        jScrollPane4.setViewportView(Jpast_history);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, jScrollPane3, jScrollPane4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bauhaus", 1, 18)); // NOI18N
        jLabel1.setText("Patient History ");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examination", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel12.setText("General");

        jLabel13.setText("Systemie");

        jLabel14.setText("Local");

        Jgeneral.setFont(new java.awt.Font("Bauhaus Thin", 0, 14)); // NOI18N
        Jgeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JgeneralActionPerformed(evt);
            }
        });

        Jsystemine.setFont(new java.awt.Font("Bauhaus Thin", 0, 14)); // NOI18N

        Jlocal.setFont(new java.awt.Font("Bauhaus Thin", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jlocal, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(Jsystemine)
                    .addComponent(Jgeneral))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Jgeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jsystemine, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Jgeneral, Jlocal, Jsystemine});

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examination", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel15.setText("LAB:");

        jLabel16.setText("X-Ray");

        jLabel17.setText("CT");

        jLabel18.setText("MRI");

        Jmri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlab, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(2, 2, 2)
                .addComponent(Jxray, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(2, 2, 2)
                .addComponent(Jct, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(2, 2, 2)
                .addComponent(Jmri, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Jlab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Jxray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(Jct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(Jmri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Examination", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Soft Tissue");

        jLabel24.setText("Side");

        jLabel25.setText("Anatomic Location");

        jLabel26.setText("Sub location");

        jLabel27.setText("Pathology");

        jLabel28.setText("Classification");

        jLabel29.setText("Other");

        Jsoft_tissue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CLOSED", "G I", "G II", "G III A", "G III B", "G III C", "SPECIAL" }));

        Jside.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Right", "Left", "Bilateral", "Spine", "Pelvis" }));

        Janatomic_location.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANKLE", "ARM", "BB FOREARM", "CALF", "CLAVICLE", "DORSAL SPINE", "ELBOW", "FEMUR", "FIBULA", "FLANK", "FOOT", "HAND", "HIP", "HUMERUS", "KNEE", "LEG", "LUMBAR SPINE", "ILIUM", "ISCHIUM", "PUBIS", "ACETABULUM", "RADIUS", "SHOULDER", "TIBIA", "ULNA", "WRIST" }));

        Jsub_location.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC JOINT", "ACETABULUM", "LEVEL ", "DISTAL", "INTERTROCHANTERIC", "INTERCONDYLAR", "ILIAC BLADE", "JOINT", "LATERAL CONDYLE", "LATERAL END", "LATERAL MALLEOLUS", "METACARPLE", "MEDIAL CONDYLE", "MEDIAL EPICONDYLE", "MENISCUS LATERAL ", "MENISCUS MEDIAL", "OLECARNON", "PARAVERTEBRAL", "PATELLA", "PHALYNX NO:", "PILON", "PLATEAU", "POPLITEAL", "PRE PATELLAR", "RAMI", "SHAFT", "SOFT TISSUE", "STYLOID PROCESS", "SUBTALAR JOINT", "SUBTROCHANTERIC", "SUPRACONDYLAR", "NECK ", "TUBERCULOSIS", "TIBIO TALAR", "TOE NO:", "METATARSAL NO:", "LUMBAR NO:", "DORSAL NO:" }));

        Jpathology.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FRACTURE", "DISLOCATION", "OSTEOMYELITIS", "SEPTIC ARTHRITIS", "SUBLUXATION", "REACTIVE ARTHRITIS", "ARTHRITIS", "TUBERCULOSIS", "INJURY", "WOUND", "CONTUSION", "ABRASSION", "TUMOR" }));

        Jclassification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JclassificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel24))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Jsoft_tissue, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Jside, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(Jpathology, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(Jother, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(Janatomic_location, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Jclassification, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(Jsub_location, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jsoft_tissue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Janatomic_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jsub_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jpathology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jclassification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jbtnsave.setBackground(new java.awt.Color(255, 255, 255));
        Jbtnsave.setMnemonic('s');
        Jbtnsave.setText("Save ");
        Jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnsaveActionPerformed(evt);
            }
        });

        Jbtnupdate.setBackground(new java.awt.Color(255, 255, 255));
        Jbtnupdate.setMnemonic('u');
        Jbtnupdate.setText("Update");
        Jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnupdateActionPerformed(evt);
            }
        });

        Jbtnshow_discharge_module.setBackground(new java.awt.Color(255, 255, 255));
        Jbtnshow_discharge_module.setMnemonic('d');
        Jbtnshow_discharge_module.setText("Show Discharge Module");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setMnemonic('p');
        jButton1.setText("Print this Document");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Jbtnshow_discharge_module, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(Jbtnsave)
                        .addGap(18, 18, 18)
                        .addComponent(Jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jbtnshow_operation_module, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel4, jPanel5});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtnshow_discharge_module)
                    .addComponent(jButton1)
                    .addComponent(Jbtnsave)
                    .addComponent(Jbtnupdate)
                    .addComponent(Jbtnshow_operation_module))
                .addContainerGap())
        );

        jScrollPane5.setViewportView(jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JnameActionPerformed

    private void JtelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtelephoneActionPerformed

    private void JageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JageActionPerformed

    private void JgeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JgeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JgeneralActionPerformed

    private void JmriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmriActionPerformed

    private void JclassificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JclassificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JclassificationActionPerformed

    private void JbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnupdateActionPerformed

        
        try{
            
            Connection con;
            con = DBConnection.getConnection();
            
           String qry = "update history_table set name=?,age=?,sex=?,dob=?,address=?,telephone=?,chief_complain=?,history_of_illness=?,past_history=?,general=?,systemine=?,local=?,lab=?,xray=?,ct=?,mri=?,soft_tissue=?,side=?,anatomic_location=?,sub_location=?,pathology=?,classification=?,other=?,mgmt_procedure=?,implant=?,mgmt_other=?,date=? where patient_id=?";
           
           PreparedStatement pst = con.prepareStatement(qry);
           pst.setString(1, Jname.getText());
           pst.setInt(2,Integer.parseInt(Jage.getText()));
           pst.setString(3, Jsex.getText());
           pst.setString(4, Jdob.getText());
           pst.setString(5, Jaddress.getText());
           pst.setString(6, Jtelephone.getText());
           pst.setString(7, Jchief_complain.getText());
           pst.setString(8, Jhistory_of_illness.getText());
           pst.setString(9, Jpast_history.getText());
           pst.setString(10, Jgeneral.getText());
           pst.setString(11, Jsystemine.getText());
           pst.setString(12, Jlocal.getText());
           pst.setString(13, Jlab.getText());
           pst.setString(14, Jxray.getText());
           pst.setString(15, Jct.getText());
           pst.setString(16, Jmri.getText());
           pst.setString(17, Jsoft_tissue.getSelectedItem().toString());
           pst.setString(18, Jside.getSelectedItem().toString());
           pst.setString(19, Janatomic_location.getSelectedItem().toString());
           pst.setString(20, Jsub_location.getSelectedItem().toString());
           pst.setString(21, Jpathology.getSelectedItem().toString());
           pst.setString(22, Jclassification.getText());
           pst.setString(23, Jother.getText());
           pst.setString(24, Jprocedure.getSelectedItem().toString());
           pst.setString(25, Jimplant.getSelectedItem().toString());
           pst.setString(26, Jmgmt_other.getText());
           pst.setString(27, Jdate.getText());
           pst.setInt(28, patient.getPatient_id());
         
         pst.execute();
         JOptionPane.showMessageDialog(null, "Successful Update "+patient.getPatient_id());
         
         con.close();
         
            
            
        
        }
        catch(Exception e){
            System.out.println(e);
        }















// TODO add your handling code here:
    }//GEN-LAST:event_JbtnupdateActionPerformed

    private void Jbtnshow_operation_moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtnshow_operation_moduleActionPerformed

        OTDBO checkdb = new OTDBO();
        OperationTeam ot = checkdb.getOtteam(patient.getPatient_id());
        
        
        
        
        if(patient.getPatient_id()==ot.getPatient_id()){
            JOptionPane.showMessageDialog(null, "Existing patient");
                    new OperationFrame(patient.getPatient_id());
        }
        
        else {
            JOptionPane.showMessageDialog(null, "New patient");
            new OperationFrame(patient.getPatient_id(),true);
        }











// TODO add your handling code here:
    }//GEN-LAST:event_Jbtnshow_operation_moduleActionPerformed

    private void JbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnsaveActionPerformed
        
        patient = new Patient();
        patient.setPatient_id(Integer.parseInt(Jpatient_id.getText()));
        patient.setName(Jname.getText()); 
        patient.setAge(Integer.parseInt(Jage.getText()));
        patient.setSex(Jsex.getText());
        patient.setDob(Jdob.getText());
        patient.setAddress(Jaddress.getText());
        patient.setTelephone(Jtelephone.getText());
        patient.setChief_complain(Jchief_complain.getText());
        patient.setHistory_of_illness(Jhistory_of_illness.getText());
        patient.setPast_history(Jpast_history.getText());
        patient.setGeneral(Jgeneral.getText());
        patient.setSystemine(Jsystemine.getText());
        patient.setLocal(Jlocal.getText());
        patient.setLab(Jlab.getText());
        patient.setXray(Jxray.getText());
        patient.setCt(Jct.getText());
        patient.setMri(Jmri.getText());
        patient.setSoft_tissue((String)Jsoft_tissue.getSelectedItem());   
        patient.setSide((String)Jside.getSelectedItem());  
        patient.setAnatomic_location((String)Janatomic_location.getSelectedItem().toString()); 
        patient.setSub_location((String)Jsub_location.getSelectedItem().toString());
        patient.setPathalogical_lesion((String)Jpathology.getSelectedItem().toString()); 
        patient.setClassification(Jclassification.getText());
        patient.setOther(Jother.getText());
        patient.setMgmt_other(Jmgmt_other.getText());
        patient.setDate(Jdate.getText());
        patient.setMgmt_procedure(Jprocedure.getSelectedItem().toString());
        patient.setImplant(Jimplant.getSelectedItem().toString());
        
        PatientDBO pdbo = new PatientDBO();
        pdbo.addPatient(patient);
          
          
//        try{
//            Connection con;
//            con = DBConnection.getConnection();
//            
////           String qry = "insert into history_table(patient_id,name,age,sex,dob,address,telephone,chief_complain,history_of_illness,past_history,general,systemine,local,lab,xray,ct,mri,soft_tissue,side,anatomic_location,sub_location,pathology,classification,other,mgmt_procedure,implant,mgmt_other,date) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
////     
//            
//           PreparedStatement pst = con.prepareStatement(qry);
//           //pst.executeQuery(qqq);
//           pst.setInt(1, patient.getPatient_id());
//           pst.setString(2, patient.getName());
//           pst.setInt(3,patient.getAge());
//           pst.setString(4, patient.getSex());
//           pst.setString(5, patient.getDob());
//           pst.setString(6, patient.getAddress());
//           pst.setString(7, patient.getTelephone());
//           pst.setString(8, patient.getChief_complain());
//           pst.setString(9, patient.getHistory_of_illness());
//           pst.setString(10, patient.getPast_history());
//           pst.setString(11, patient.getGeneral());
//           pst.setString(12, patient.getSystemine());
//           pst.setString(13, patient.getLocal());
//           pst.setString(14, patient.getLab());
//           pst.setString(15, patient.getXray());
//           pst.setString(16, patient.getCt());
//           pst.setString(17, patient.getMri());
//           pst.setString(18, patient.getSoft_tissue());
//           pst.setString(19, patient.getSide());
//           pst.setString(20, patient.getAnatomic_location());
//           pst.setString(21, patient.getSub_location());
//           pst.setString(22, patient.getPathalogical_lesion());
//           pst.setString(23, patient.getClassification());
//           pst.setString(24, patient.getOther());
//           pst.setString(25, patient.getMgmt_procedure());
//           pst.setString(26, patient.getImplant());
//           pst.setString(27, patient.getMgmt_other());
//           pst.setString(28, patient.getDate());
//           
//         
//         pst.execute();
//            con.close();
//        JOptionPane.showMessageDialog(null, "Saved Successfully");
//        
//        }catch(Exception e){
//         JOptionPane.showMessageDialog(null, "Errror Occured");
//        }
        
        


// TODO add your handling code here:
    }//GEN-LAST:event_JbtnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Jaddress;
    private javax.swing.JTextField Jage;
    private javax.swing.JComboBox Janatomic_location;
    private javax.swing.JButton Jbtnsave;
    private javax.swing.JButton Jbtnshow_discharge_module;
    private javax.swing.JButton Jbtnshow_operation_module;
    private javax.swing.JButton Jbtnupdate;
    private javax.swing.JTextArea Jchief_complain;
    private javax.swing.JTextField Jclassification;
    private javax.swing.JTextField Jct;
    private javax.swing.JTextField Jdate;
    private javax.swing.JTextField Jdob;
    private javax.swing.JTextField Jgeneral;
    private javax.swing.JTextArea Jhistory_of_illness;
    private javax.swing.JComboBox Jimplant;
    private javax.swing.JTextField Jlab;
    private javax.swing.JTextField Jlocal;
    private javax.swing.JLabel Jmgmg_other;
    private javax.swing.JTextField Jmgmt_other;
    private javax.swing.JTextField Jmri;
    private javax.swing.JTextField Jname;
    private javax.swing.JTextField Jother;
    private javax.swing.JTextArea Jpast_history;
    private javax.swing.JComboBox Jpathology;
    private javax.swing.JTextField Jpatient_id;
    private javax.swing.JComboBox Jprocedure;
    private javax.swing.JTextField Jsex;
    private javax.swing.JComboBox Jside;
    private javax.swing.JComboBox Jsoft_tissue;
    private javax.swing.JComboBox Jsub_location;
    private javax.swing.JTextField Jsystemine;
    private javax.swing.JTextField Jtelephone;
    private javax.swing.JTextField Jxray;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics grphcs, PageFormat pf, int i) throws PrinterException {
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
